import{a as p,S as h,i as m}from"./assets/vendor-b0d10f48.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function f(a,t){p.defaults.baseURL="https://pixabay.com/api/";const s=new URLSearchParams({key:"44427919-32b813221576803201dca5eed",q:a,image_type:"photo",orientation:"horisontal",safesearch:"true",per_page:15,page:t});try{return(await p.get("",{params:s})).data}catch{iziToast.show({iconUrl:imageUrl,title:"Error",titleColor:"white",message:"Error!",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",position:"topRight",theme:"dark"})}}function L(a){const{webformatURL:t,largeImageURL:s,tags:i,likes:e,views:r,comments:l,downloads:w}=a;return`<li class="gallery-item">
          <a class="gallery-link" href="${s}">
            <img class="gallery-image" src="${t}" alt="${i}" />
            <div class="gallery-describe">
              <p class="gallery-text">Likes <br>${e}</p>
              <p class="gallery-text">Views<br>${r}</p>
              <p class="gallery-text">Comments<br>${l}</p>
              <p class="gallery-text">Downloads<br>${w}</p>
            </div>
          </a>
        </li>`}function y(a){return a.hits.map(L).join("")}const d="/goit-js-hw-12/assets/javascript-61de9f5c.svg",o={galleryElem:document.querySelector(".gallery"),searchBtn:document.querySelector(".search-btn"),formElem:document.querySelector(".search-form"),inputElem:document.querySelector(".search-input"),galleryItem:document.querySelector(".gallery-item"),loader:document.querySelector(".loader"),btnLoadMore:document.querySelector(".btn-load-more")};let c="",n=1,g=1;const E=15;new h(".gallery a",{captionPosition:"bottom",captionsData:"alt",captionDelay:250});o.formElem.addEventListener("submit",async a=>{if(a.preventDefault(),n=1,S(),c=o.inputElem.value.trim(),c.length<=0)m.show({iconUrl:d,title:"Error",titleColor:"white",message:"This field must be filled in",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",position:"topRight",theme:"dark"}),u(),o.formElem.reset();else{try{const t=await f(c,n);if(console.log(t),g=Math.ceil(t.total/E),console.log(g),t.hits.length>0){const s=y(t);o.galleryElem.innerHTML=s,b(),new h(".gallery-item a",{captionsData:"alt",captionDelay:250}).refresh()}else m.show({iconUrl:d,title:"Error",titleColor:"white",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",position:"topRight",theme:"dark"}),u()}catch{m.show({iconUrl:d,title:"Error",titleColor:"white",message:"Error!",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",position:"topRight",theme:"dark"})}u(),o.formElem.reset()}});o.btnLoadMore.addEventListener("click",async a=>{a.preventDefault(),n++;const t=await f(c,n),s=y(t);o.galleryElem.insertAdjacentHTML("beforeend",s),b()});function S(){o.loader.classList.remove("hidden")}function u(){o.loader.classList.add("hidden")}function b(){n>=g?C():v()}function v(){o.btnLoadMore.classList.remove("hidden")}function C(){o.btnLoadMore.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
