import{a as h,S as p,i as c}from"./assets/vendor-b0d10f48.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();async function f(a,t){h.defaults.baseURL="https://pixabay.com/api/";const s=new URLSearchParams({key:"44427919-32b813221576803201dca5eed",q:a,image_type:"photo",orientation:"horisontal",safesearch:"true",per_page:15,page:t});try{return(await h.get("",{params:s})).data}catch{iziToast.show({iconUrl:imageUrl,title:"Error",titleColor:"white",message:"Error!",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",position:"topRight",theme:"dark"})}}function E(a){const{webformatURL:t,largeImageURL:s,tags:i,likes:e,views:o,comments:l,downloads:w}=a;return`<li class="gallery-item">
          <a class="gallery-link" href="${s}">
            <img class="gallery-image" src="${t}" alt="${i}" />
            <div class="gallery-describe">
              <p class="gallery-text">Likes <br>${e}</p>
              <p class="gallery-text">Views<br>${o}</p>
              <p class="gallery-text">Comments<br>${l}</p>
              <p class="gallery-text">Downloads<br>${w}</p>
            </div>
          </a>
        </li>`}function y(a){return a.hits.map(E).join("")}const m="/goit-js-hw-12/assets/javascript-61de9f5c.svg",r={galleryElem:document.querySelector(".gallery"),searchBtn:document.querySelector(".search-btn"),formElem:document.querySelector(".search-form"),inputElem:document.querySelector(".search-input"),galleryItem:document.querySelector(".gallery-item"),loader:document.querySelector(".loader"),btnLoadMore:document.querySelector(".btn-load-more"),loaderMore:document.querySelector(".loader-more")};let d="",n=1,b=1;const S=15;new p(".gallery a",{captionPosition:"bottom",captionsData:"alt",captionDelay:250});r.formElem.addEventListener("submit",async a=>{if(a.preventDefault(),n=1,v(),d=r.inputElem.value.trim(),d.length<=0)c.show({iconUrl:m,title:"Error",titleColor:"white",message:"This field must be filled in",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",position:"topRight",theme:"dark"}),u(),r.formElem.reset();else{try{g();const t=await f(d,n);if(b=Math.ceil(t.total/S),t.hits.length>0){const s=y(t);r.galleryElem.innerHTML=s,L(),new p(".gallery-item a",{captionsData:"alt",captionDelay:250}).refresh()}else c.show({iconUrl:m,title:"Error",titleColor:"white",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",position:"topRight",theme:"dark"}),u()}catch{c.show({iconUrl:m,title:"Error",titleColor:"white",message:"Error!",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",position:"topRight",theme:"dark"})}u(),r.formElem.reset()}});r.btnLoadMore.addEventListener("click",async a=>{a.preventDefault(),n++,g(),C();const t=await f(d,n),s=y(t);r.galleryElem.insertAdjacentHTML("beforeend",s),x(),L(),M()});function v(){r.loader.classList.remove("hidden")}function u(){r.loader.classList.add("hidden")}function C(){r.loaderMore.classList.remove("hidden")}function M(){r.loaderMore.classList.add("hidden")}function L(){n>=b?(g(),c.info({message:"We're sorry, but you've reached the end of search results.",messageColor:"black",messageSize:"16px",backgroundColor:"#00ffff",position:"bottomRight"})):k()}function k(){r.btnLoadMore.classList.remove("hidden")}function g(){r.btnLoadMore.classList.add("hidden")}function x(){const t=r.galleryElem.children[0].getBoundingClientRect().height;window.scrollBy({top:t*2.4,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
